---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nginx-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs
